name: Wazuh docker testing images building workflow.


on:
  push:
    paths:
      - 'unattended_scripts/**'
      - 'unattended_scripts/tools/**'
      - '.github/**'

  pull_request:
    paths:
      - 'unattended_scripts/**'
      - 'unattended_scripts/tools/**'
      - '.github/**'

jobs:

  docker_build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Build and push CentOS_7
        id: docker_build_centos_7
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/centos-7-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/CentOS/7/Dockerfile'

        name: Build and push CentOS_8
        id: docker_build_centos_8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/centos-8-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/CentOS/8/Dockerfile'

        name: Build and push AmazonLinux_2
        id: docker_build_amazonlinux 2
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/amazonlinux-2-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/AmazonLinux/2/Dockerfile'

        name: Build and push Ubuntu_Focal
        id: docker_build_ubuntu_focal
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/ubuntu-focal-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/Ubuntu/Focal/Dockerfile'

        name: Build and push Ubuntu_Bionic
        id: docker_build_ubuntu_bionic
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/ubuntu-bionic-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/Ubuntu/Bionic/Dockerfile'

        name: Build and push Debian_Bullseye
        id: docker_build_debian_bullseye
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/debian-bullseye-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/Debian/Bullseye/Dockerfile'

        name: Build and push Debian_Buster
        id: docker_build_debian_buster
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/debian-buster-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/Debian/Buster/Dockerfile'

        name: Build and push Debian_Stretch
        id: docker_build_debian_stretch
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/debian-stretch-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/Debian/Stretch/Dockerfile'

        name: Build and push OracleLinux_7
        id: docker_build_oraclelinux_7
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/oraclelinux-7-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/OracleLinux/7/Dockerfile'

        name: Build and push OracleLinux_8
        id: docker_build_oraclelinux_8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/oraclelinux-8-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/OracleLinux/8/Dockerfile'

        name: Build and push Debian_Jessie
        id: docker_build_debian_jessie
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wazuh/debian-jessie-unattended-base:latest
          context: './.github/actions/Tests/Unattended'
          file: './.github/actions/Docker/Debian/Jessie/Dockerfile'















