name: pr-review
on: [pull_request]

jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Set Artifacts
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: set tool
        uses: './.github/actions/get-tools/'
        with: 
          tool: steps.changed_files.outputs.all
      - name: Build Matrix
        id: set-matrix
        run: |
          echo "::set-output name=tools_matrix::[${{ env.VAR }}]"
    outputs:
      tools_matrix: ${{ steps.set-matrix.outputs.tools_matrix }}
  
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: get-artifacts
    strategy:
      matrix: 
        tool: ${{ fromJson(needs.get-artifacts.outputs.tools_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Generate artifacts
        uses: './.github/actions/generate-artifacts/'
        with: 
          artifact: "${{ matrix.tool }}"
      - name: Checkout
        run: ls -la unattended_installer
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_generated
          path: |
            unattended_installer/**tool.sh
            unattended_installer/**install.sh
          
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    needs: Builder-Scripts
    steps:
      - uses: actions/checkout@v1
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: test
        run: |
          pwd
          ls -ls
          ls -la artifacts_generated
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: |
            "artifacts_generated"
            "wpk"
          pattern: "*.sh"
          #exclude: "artifacts-generated/*.md"
          #check_all_files_with_shebangs: "false"
          fail_on_error: "true"
