name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Get Files
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: set cert
        if: contains(steps.changed_files.outputs.all, 'cert_tool')
        run: |
          if [ -z "${{ env.VAR }}" ]; then
            echo 'VAR=\"cert-tool\"' >> $GITHUB_ENV
          else
            echo 'VAR=${{ env.VAR }},\"cert-tool\"' >> $GITHUB_ENV
          fi
      - name: set password
        if: contains(steps.changed_files.outputs.all, 'passwords_tool')
        run: |
          if [ -z "${{ env.VAR }}" ]; then
            echo 'VAR=\"passwords-tool\"' >> $GITHUB_ENV
          else
            echo 'VAR=${{ env.VAR }},\"passwords-tool\"' >> $GITHUB_ENV
          fi
      - name: set all
        if: contains(steps.changed_files.outputs.all, 'common_functions')
        run: |
          echo 'VAR=\"cert-tool\",\"passwords-tool\",\"installer\"' >> $GITHUB_ENV
      - name: set builder
        if: contains(steps.changed_files.outputs.all, 'builder.sh')
        run: |
          if [ -z "${{ env.VAR }}" ]; then
            echo 'VAR=\"builder.sh\"' >> $GITHUB_ENV
          else
            echo 'VAR=${{ env.VAR }},\"builder.sh\"' >> $GITHUB_ENV
          fi
      - name: Build Matrix
        id: set-matrix
        run: |
          echo "::set-output name=tools_matrix::[${{ env.VAR }}]"
    outputs:
      tools_matrix: ${{ steps.set-matrix.outputs.tools_matrix }}
  
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: get-files
    strategy:
      matrix: 
        tool: ${{ fromJson(needs.get-files.outputs.tools_matrix) }}
    steps:
      - name: builder-sh
        run: |
          echo ${{ matrix.tool }}
          pwd
          ls -la
          bash unattended_installer/builder.sh -${{ matrix.tool }}
