name: Test Wazuh indexer on upgrade - Debian
on:
  push:
    branches:
      - 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
  pull_request:
    paths:
      - 'stack/indexer/deb/debian/postrm'
      - 'stack/indexer/deb/debian/postinst'
      - 'stack/indexer/deb/debian/preinst'
      - '.github/workflows/test-indexer.yml'
  workflow_dispatch:

jobs:
  Test-debian-indexer-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Download wazuh-indexer release package
        run: |
          curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
          echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee -a /etc/apt/sources.list.d/wazuh.list
          sudo apt-get update
      - uses: actions/checkout@v3
        with:
          ref: 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
      - uses: actions/checkout@v3
        with:
          ref: 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
      - name: Build/Download wazuh-indexer issue-branch package and set env variable
        working-directory: ./stack/indexer/deb
        run: |
          wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=12AgpaYEfEEuucCl-rKNClfHzkJ8fZFvb' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=12AgpaYEfEEuucCl-rKNClfHzkJ8fZFvb" -O wazuh-indexer_4.5.0-1_amd64.deb && rm -rf /tmp/cookies.txt
          echo "PACKAGE_NAME=$(ls | grep .deb | head -n 1)" >> $GITHUB_ENV
          echo $(pwd)
      - name: Display env variable and ls
        working-directory: ./stack/indexer/deb
        run: |
          echo $PACKAGE_NAME
          echo $(ls)
          echo $(pwd)
          sudo cp ./$PACKAGE_NAME /home/runner/work/wazuh-packages/$PACKAGE_NAME
      - name: Move package to home and run script
        run: |
          echo $(ls ~/)
          echo $(ls /home/runner/wazuh-packages/)
          echo $(pwd)
          sudo bash .github/actions/upgrade-indexer/upgrade-indexer-debian.sh $PACKAGE_NAME