name: Test Wazuh indexer on upgrade - Debian
on:
  push:
    branches:
      - 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
  pull_request:
    paths:
      - 'stack/indexer/deb/debian/postrm'
      - 'stack/indexer/deb/debian/postinst'
      - 'stack/indexer/deb/debian/preinst'
      - '.github/workflows/test-indexer.yml'
  workflow_dispatch:

jobs:
  Test-debian-indexer-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Download wazuh-indexer release package
        run: |
          curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
          echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee -a /etc/apt/sources.list.d/wazuh.list
          sudo apt-get update
      - uses: actions/checkout@v3
        with:
          ref: 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
      - uses: actions/checkout@v3
        with:
          ref: 1850-wazuh-indexer-preserve-config-files-upon-upgrade-master
      - name: Build wazuh-indexer issue-branch package and set env variable
        working-directory: ./stack/indexer/deb
        run: |
          sudo ./build_package.sh
          echo "PACKAGE_NAME=$(ls ./output | grep .deb | head -n 1)" >> $GITHUB_ENV
      - name: Display env variable and move new package
        working-directory: ./stack/indexer/deb
        run: |
          echo $PACKAGE_NAME
          sudo cp ./output/$PACKAGE_NAME $GITHUB_WORKSPACE/$PACKAGE_NAME
      - name: Run script
        run: |
          sudo bash .github/actions/upgrade-indexer/upgrade-indexer-debian.sh $PACKAGE_NAME